export { default as AddCategoryModal } from "./ui/AddCategory";
export { default as EditCategoryModal } from "./ui/EditCategory";
export { default as AddNomenclatureModal } from "./ui/AddNomenclature";
export { default as EditNomenclatureModal } from "./ui/EditNomenclature";
export { default as AddOrganizations } from "./ui/AddOrganizations";
export { default as EditOrganizations } from "./ui/EditOrganizations";
export { default as EditContracts } from "./ui/EditContracts";
export { default as AddContracts } from "./ui/AddContracts";
export { default as EditWarehouses } from "./ui/EditWarehouses";
export { default as AddWarehouses } from "./ui/AddWarehouses";
export { default as AddWarehousesDocs } from "./ui/AddWarehousesDocs";
export { default as EditWarehousesDocs } from "./ui/EditWarehousesDocs";
export { default as AddDocsPutchases } from "./ui/AddDocsPurchases";
export { default as EditDocsPurchasesModal } from "./ui/EditDocsPurchases"
export { default as AddPrice } from "./ui/AddPrice";
export { default as EditPrice } from "./ui/EditPrice";
export { default as AddLoyalitySetting } from "./ui/AddLoyalitySetting";
export { default as EditLoyalitySetting } from "./ui/EditLoyalitySetting";
export { default as SplitPayment } from './ui/SplitPayment'
export { default as EditContragents } from "./ui/EditCA"
export { default as EditPayment } from "./ui/EditPayment"
export { default as CreateLoyalityCard } from "./ui/CreateLoyalityCard"
export { default as CreatePayment } from "./ui/CreatePayment"
export { default as EditDocsSales } from "./ui/EditDocSales"
export { default as CreateBonusTransaction } from "./ui/CreateBonusTransaction"
export { default as EditBonusTransaction } from "./ui/EditBonusTransaction"
export { default as CreateIntegration } from "./ui/IntegrationsModal"
export { default as CreatePaybox } from "./ui/CreatePboxModal"
export { default as AddProject } from "./ui/AddProject"
export { default as AddContragents } from "./ui/AddContragents"
export { default as EditDocsPurchases } from "./ui/EditDocsPurchases"
export { default as EditDocsWarehouse } from "./ui/EditDocWarehouse"
export { default as CreateDocsWarehouse } from "./ui/CreateDocsWarehouse"
export { default as CreateDocsPurchases } from "./ui/CreateDocsPurchases"
export { default as CreateDocsSales } from "./ui/CreateDocsSales"
export { default as RaspilView } from "./ui/RaspilView"