export { default as TableCategoriesPage } from "./TableCategories/ui/TableCategories";
export { default as TableNomenclature } from "./TableNomenclature/ui/TableNomenclature";
export { default as TableOrganizations } from "./TableOrganizations/ui/TableOrganizations";
export { default as TableContracts } from "./TableContracts/ui/TableContracts";
export { default as TableWarehouses } from "./TableWarehouses/ui/TableWarehouses";
export { default as TableWarehousesDocs } from "./TableWarehousesDocs/TableWarehousesDocs";
export { default as TablePrices } from "./TablePrices/ui/TablePrices";
export { default as TableDocsPurchases } from "./TableDocsPurchases/ui/TableDocsPurchases";
export { default as TablePricesHandsontable } from "./TablePricesHandsontable/ui/TablePricesHandsontable";
export { default as TableLoyalitySettings } from "./TableLoyalitySettings/ui/TableLoyalitySettings";
export { default as TableLoyalityReport } from "./TableLoyalityReport/ui/TableLoyalityReport";
export { default as TablePayments } from "./TablePayments/Payments";
export { default as TableLoyalityCards } from "./TableLoyalityCards/LoyalityCards"
export { default as TableContragents } from "./TableContragents/Contragents"
export { default as TableProjects } from "./TableProjects/Projects"
export { default as TablePurchases } from "./TablePurchases/Purchases"
export { default as TableDocsWarehouse } from "./TableDocsWarehouse/DocsWarehouse"
export { default as TablePayboxes } from "./TablePayboxes/Payboxes"
export { default as TableUsers } from "./TableUsers/Users"
export { default as TableEvents } from "./TableEvents/Events"
export { default as TableIntegrations } from "./TableIntegrations/Integrations"
export { default as TableDocsSales } from "./TableDocsSales/DocsSales"
export { default as TableWarehousesBalance } from "./TableWarehousesBalance/WarehousesBalance"
export { default as TableLoyalityTransactions } from "./TableLoyalityTransactions/LoyalityTransactions"
export { default as TableAnalystics } from "./TableAnalystics/index"