"""add_view_events_table

Revision ID: 92eed9522fb9
Revises: e5614f22c878
Create Date: 2025-10-11 08:40:05.010180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eed9522fb9'
down_revision = 'e5614f22c878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('listing_pos', sa.Integer(), nullable=True),
    sa.Column('listing_page', sa.Integer(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_events_id'), 'view_events', ['id'], unique=False)
    op.drop_index('ix_diadok_install_id', table_name='diadok_install')
    op.drop_table('diadok_install')
    op.create_unique_constraint(None, 'amo_contacts', ['amo_install_group_id', 'ext_id'])
    op.drop_constraint('amo_contacts_double_orig_id_fkey', 'amo_contacts_double', type_='foreignkey')
    op.create_foreign_key(None, 'amo_contacts_double', 'amo_contacts', ['orig_id'], ['id'])
    op.drop_constraint('amo_entity_custom_fields_contact_id_fkey', 'amo_entity_custom_fields', type_='foreignkey')
    op.create_foreign_key(None, 'amo_entity_custom_fields', 'amo_contacts', ['contact_id'], ['id'])
    op.create_unique_constraint(None, 'amo_lead_pipelines', ['amo_install_group_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_lead_statuses', ['pipeline_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_leads', ['amo_install_group_id', 'amo_id'])
    op.drop_constraint('amo_table_contacts_amo_id_fkey', 'amo_table_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'amo_table_contacts', 'amo_contacts', ['amo_id'], ['id'])
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    op.drop_index('idx_cashboxes_city', table_name='cashboxes')
    op.drop_index('idx_cashboxes_public', table_name='cashboxes')
    op.create_foreign_key(None, 'categories', 'pictures', ['photo_id'], ['id'])
    op.drop_index('idx_docs_sales_cashbox_dated_id_not_deleted', table_name='docs_sales')
    op.drop_index('idx_docs_sales_id_cashbox_not_deleted', table_name='docs_sales')
    op.drop_index('idx_docs_sales_delivery_info_delivery_date_docs_sales_id', table_name='docs_sales_delivery_info')
    op.drop_index('idx_favorites_created_at', table_name='favorites')
    op.drop_index('idx_favorites_entity', table_name='favorites')
    op.drop_index('idx_favorites_phone_hash', table_name='favorites')
    op.drop_index('idx_favorites_unique', table_name='favorites')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_global_categories_id'), 'global_categories', ['id'], unique=False)
    op.drop_index('idx_mp_orders_created_at', table_name='mp_orders')
    op.drop_index('idx_mp_orders_customer_phone', table_name='mp_orders')
    op.drop_index('idx_mp_orders_status', table_name='mp_orders')
    op.create_index(op.f('ix_mp_orders_id'), 'mp_orders', ['id'], unique=False)
    op.drop_index('idx_nomenclature_city', table_name='nomenclature')
    op.drop_index('idx_nomenclature_public', table_name='nomenclature')
    op.drop_index('idx_qr_codes_active', table_name='qr_codes')
    op.drop_index('idx_qr_codes_entity', table_name='qr_codes')
    op.drop_index('idx_qr_codes_hash', table_name='qr_codes')
    op.create_index(op.f('ix_qr_codes_id'), 'qr_codes', ['id'], unique=False)
    op.drop_index('idx_reviews_created_at', table_name='reviews')
    op.drop_index('idx_reviews_location_id', table_name='reviews')
    op.drop_index('idx_reviews_rating', table_name='reviews')
    op.drop_index('idx_reviews_status', table_name='reviews')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_segments_tags_id'), 'segments_tags', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bot_bill_approvers_id'), 'tg_bot_bill_approvers', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bot_bills_id'), 'tg_bot_bills', ['id'], unique=False)
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tg_bot_bills_id'), table_name='tg_bot_bills')
    op.drop_index(op.f('ix_tg_bot_bill_approvers_id'), table_name='tg_bot_bill_approvers')
    op.drop_index(op.f('ix_segments_tags_id'), table_name='segments_tags')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_index('idx_reviews_status', 'reviews', ['status'], unique=False)
    op.create_index('idx_reviews_rating', 'reviews', ['rating'], unique=False)
    op.create_index('idx_reviews_location_id', 'reviews', ['location_id'], unique=False)
    op.create_index('idx_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.drop_index(op.f('ix_qr_codes_id'), table_name='qr_codes')
    op.create_index('idx_qr_codes_hash', 'qr_codes', ['qr_hash'], unique=False)
    op.create_index('idx_qr_codes_entity', 'qr_codes', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_qr_codes_active', 'qr_codes', ['is_active'], unique=False)
    op.create_index('idx_nomenclature_public', 'nomenclature', ['public'], unique=False)
    op.create_index('idx_nomenclature_city', 'nomenclature', ['city'], unique=False)
    op.drop_index(op.f('ix_mp_orders_id'), table_name='mp_orders')
    op.create_index('idx_mp_orders_status', 'mp_orders', ['status'], unique=False)
    op.create_index('idx_mp_orders_customer_phone', 'mp_orders', ['customer_phone'], unique=False)
    op.create_index('idx_mp_orders_created_at', 'mp_orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_global_categories_id'), table_name='global_categories')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_index('idx_favorites_unique', 'favorites', ['phone_hash', 'entity_type', 'entity_id'], unique=False)
    op.create_index('idx_favorites_phone_hash', 'favorites', ['phone_hash'], unique=False)
    op.create_index('idx_favorites_entity', 'favorites', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_favorites_created_at', 'favorites', ['created_at'], unique=False)
    op.create_index('idx_docs_sales_delivery_info_delivery_date_docs_sales_id', 'docs_sales_delivery_info', ['delivery_date', 'docs_sales_id'], unique=False)
    op.create_index('idx_docs_sales_id_cashbox_not_deleted', 'docs_sales', ['id', 'cashbox'], unique=False)
    op.create_index('idx_docs_sales_cashbox_dated_id_not_deleted', 'docs_sales', ['cashbox', 'dated', 'id'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index('idx_cashboxes_public', 'cashboxes', ['public'], unique=False)
    op.create_index('idx_cashboxes_city', 'cashboxes', ['city'], unique=False)
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'amo_table_contacts', type_='foreignkey')
    op.create_foreign_key('amo_table_contacts_amo_id_fkey', 'amo_table_contacts', 'amo_contacts', ['amo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_leads', type_='unique')
    op.drop_constraint(None, 'amo_lead_statuses', type_='unique')
    op.drop_constraint(None, 'amo_lead_pipelines', type_='unique')
    op.drop_constraint(None, 'amo_entity_custom_fields', type_='foreignkey')
    op.create_foreign_key('amo_entity_custom_fields_contact_id_fkey', 'amo_entity_custom_fields', 'amo_contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_contacts_double', type_='foreignkey')
    op.create_foreign_key('amo_contacts_double_orig_id_fkey', 'amo_contacts_double', 'amo_contacts', ['orig_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_contacts', type_='unique')
    op.create_table('diadok_install',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name='diadok_install_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='diadok_install_pkey')
    )
    op.create_index('ix_diadok_install_id', 'diadok_install', ['id'], unique=False)
    op.drop_index(op.f('ix_view_events_id'), table_name='view_events')
    op.drop_table('view_events')
    # ### end Alembic commands ###
