"""remove some trash

Revision ID: 0037f781239f
Revises: 33de7c3df2b7
Create Date: 2025-10-18 11:06:58.740177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0037f781239f'
down_revision = '33de7c3df2b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diadok_install_id', table_name='diadok_install')
    op.drop_table('diadok_install')
    op.create_unique_constraint(None, 'amo_contacts', ['amo_install_group_id', 'ext_id'])
    op.drop_constraint('amo_contacts_double_orig_id_fkey', 'amo_contacts_double', type_='foreignkey')
    op.create_foreign_key(None, 'amo_contacts_double', 'amo_contacts', ['orig_id'], ['id'])
    op.drop_constraint('amo_entity_custom_fields_contact_id_fkey', 'amo_entity_custom_fields', type_='foreignkey')
    op.create_foreign_key(None, 'amo_entity_custom_fields', 'amo_contacts', ['contact_id'], ['id'])
    op.create_unique_constraint(None, 'amo_lead_pipelines', ['amo_install_group_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_lead_statuses', ['pipeline_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_leads', ['amo_install_group_id', 'amo_id'])
    op.drop_constraint('amo_table_contacts_amo_id_fkey', 'amo_table_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'amo_table_contacts', 'amo_contacts', ['amo_id'], ['id'])
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    op.drop_index('idx_categories_name_trgm', table_name='categories')
    op.create_foreign_key(None, 'categories', 'pictures', ['photo_id'], ['id'])
    op.drop_index('idx_contragents_id_phone_cashbox', table_name='contragents')
    op.drop_index('idx_contragents_tags_contragent_tag', table_name='contragents_tags')
    op.drop_index('idx_docs_sales_cashbox_contragent_sum', table_name='docs_sales')
    op.drop_index('idx_docs_sales_cashbox_dated_id_not_deleted', table_name='docs_sales')
    op.drop_index('idx_docs_sales_contragent_aggregate', table_name='docs_sales')
    op.drop_index('idx_docs_sales_contragent_cashbox_deleted', table_name='docs_sales')
    op.drop_index('idx_docs_sales_id_cashbox_not_deleted', table_name='docs_sales')
    op.drop_index('idx_docs_sales_sum_include', table_name='docs_sales')
    op.drop_index('idx_docs_sales_delivery_docs_address', table_name='docs_sales_delivery_info')
    op.drop_index('idx_docs_sales_delivery_info_delivery_date_docs_sales_id', table_name='docs_sales_delivery_info')
    op.drop_index('idx_docs_sales_goods_docs_nomenclature', table_name='docs_sales_goods')
    op.drop_index('idx_docs_sales_goods_nomenclature_id', table_name='docs_sales_goods')
    op.drop_index('idx_docs_sales_tags_docs_name', table_name='docs_sales_tags')
    op.drop_index('idx_loyality_cards_contragent_balance', table_name='loyality_cards')
    op.drop_index('idx_loyality_cards_contragent_balance_filtered', table_name='loyality_cards')
    op.drop_index('idx_loyality_transactions_card_created', table_name='loyality_transactions')
    op.drop_index('idx_nomenclature_category', table_name='nomenclature')
    op.drop_index('idx_nomenclature_category_id', table_name='nomenclature')
    op.create_index(op.f('ix_segments_tags_id'), 'segments_tags', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bot_bill_approvers_id'), 'tg_bot_bill_approvers', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bot_bills_id'), 'tg_bot_bills', ['id'], unique=False)
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tg_bot_bills_id'), table_name='tg_bot_bills')
    op.drop_index(op.f('ix_tg_bot_bill_approvers_id'), table_name='tg_bot_bill_approvers')
    op.drop_index(op.f('ix_segments_tags_id'), table_name='segments_tags')
    op.create_index('idx_nomenclature_category_id', 'nomenclature', ['category', 'id'], unique=False)
    op.create_index('idx_nomenclature_category', 'nomenclature', ['category', 'id'], unique=False)
    op.create_index('idx_loyality_transactions_card_created', 'loyality_transactions', ['loyality_card_id', 'created_at'], unique=False)
    op.create_index('idx_loyality_cards_contragent_balance_filtered', 'loyality_cards', ['contragent_id', 'balance'], unique=False)
    op.create_index('idx_loyality_cards_contragent_balance', 'loyality_cards', ['contragent_id', 'balance'], unique=False)
    op.create_index('idx_docs_sales_tags_docs_name', 'docs_sales_tags', ['docs_sales_id', 'name'], unique=False)
    op.create_index('idx_docs_sales_goods_nomenclature_id', 'docs_sales_goods', ['docs_sales_id', 'nomenclature'], unique=False)
    op.create_index('idx_docs_sales_goods_docs_nomenclature', 'docs_sales_goods', ['docs_sales_id', 'nomenclature'], unique=False)
    op.create_index('idx_docs_sales_delivery_info_delivery_date_docs_sales_id', 'docs_sales_delivery_info', ['delivery_date', 'docs_sales_id'], unique=False)
    op.create_index('idx_docs_sales_delivery_docs_address', 'docs_sales_delivery_info', ['docs_sales_id', 'delivery_date'], unique=False)
    op.create_index('idx_docs_sales_sum_include', 'docs_sales', ['contragent'], unique=False)
    op.create_index('idx_docs_sales_id_cashbox_not_deleted', 'docs_sales', ['id', 'cashbox'], unique=False)
    op.create_index('idx_docs_sales_contragent_cashbox_deleted', 'docs_sales', ['contragent', 'cashbox'], unique=False)
    op.create_index('idx_docs_sales_contragent_aggregate', 'docs_sales', ['contragent', 'id', 'sum', 'created_at'], unique=False)
    op.create_index('idx_docs_sales_cashbox_dated_id_not_deleted', 'docs_sales', ['cashbox', 'dated', 'id'], unique=False)
    op.create_index('idx_docs_sales_cashbox_contragent_sum', 'docs_sales', ['cashbox', 'contragent', 'sum', 'created_at'], unique=False)
    op.create_index('idx_contragents_tags_contragent_tag', 'contragents_tags', ['contragent_id', 'tag_id'], unique=False)
    op.create_index('idx_contragents_id_phone_cashbox', 'contragents', ['id', 'phone', 'cashbox'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index('idx_categories_name_trgm', 'categories', ['name'], unique=False)
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'amo_table_contacts', type_='foreignkey')
    op.create_foreign_key('amo_table_contacts_amo_id_fkey', 'amo_table_contacts', 'amo_contacts', ['amo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_leads', type_='unique')
    op.drop_constraint(None, 'amo_lead_statuses', type_='unique')
    op.drop_constraint(None, 'amo_lead_pipelines', type_='unique')
    op.drop_constraint(None, 'amo_entity_custom_fields', type_='foreignkey')
    op.create_foreign_key('amo_entity_custom_fields_contact_id_fkey', 'amo_entity_custom_fields', 'amo_contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_contacts_double', type_='foreignkey')
    op.create_foreign_key('amo_contacts_double_orig_id_fkey', 'amo_contacts_double', 'amo_contacts', ['orig_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'amo_contacts', type_='unique')
    op.create_table('diadok_install',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name='diadok_install_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='diadok_install_pkey')
    )
    op.create_index('ix_diadok_install_id', 'diadok_install', ['id'], unique=False)
    # ### end Alembic commands ###
