"""yookassa_install_webhook

Revision ID: 01f2cfcbdb01
Revises: 7fa9039fda7c
Create Date: 2025-02-13 13:22:48.754399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f2cfcbdb01'
down_revision = '7fa9039fda7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yookassa_install_webhook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('webhook_event', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('yookassa_install_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['yookassa_install_id'], ['yookassa_install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yookassa_install_webhook_id'), 'yookassa_install_webhook', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yookassa_install_webhook_id'), table_name='yookassa_install_webhook')
    op.drop_table('yookassa_install_webhook')
    # ### end Alembic commands ###
