"""fix payment_past_edit_days

Revision ID: 03c97d9e42f7
Revises: 6783addfadde
Create Date: 2025-08-07 12:04:15.832046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c97d9e42f7'
down_revision = '6783addfadde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_tg_cashboxes', sa.Column('payment_past_edit_days', sa.Integer(), nullable=True))
    op.drop_column('tg_accounts', 'payment_past_edit_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_accounts', sa.Column('payment_past_edit_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('relation_tg_cashboxes', 'payment_past_edit_days')
    # ### end Alembic commands ###
