"""update favorites table

Revision ID: 0562eb22c3eb
Revises: 733d7fbf311e
Create Date: 2025-11-07 08:22:16.634718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0562eb22c3eb'
down_revision = '733d7fbf311e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites_nomenclatures', 'utm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites_nomenclatures', sa.Column('utm', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
