"""marketplace

Revision ID: 0917e7569759
Revises: b89cc2159913
Create Date: 2025-11-03 20:09:57.359006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0917e7569759'
down_revision = 'b89cc2159913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mp_orders', sa.Column('recipient_phone', sa.String(), nullable=True))
    op.add_column('mp_orders', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('mp_orders', sa.Column('recipient_lat', sa.Float(), nullable=True))
    op.add_column('mp_orders', sa.Column('recipient_lon', sa.Float(), nullable=True))
    op.add_column('mp_orders', sa.Column('order_type', sa.String(), server_default='self', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mp_orders', 'order_type')
    op.drop_column('mp_orders', 'recipient_lon')
    op.drop_column('mp_orders', 'recipient_lat')
    op.drop_column('mp_orders', 'recipient_name')
    op.drop_column('mp_orders', 'recipient_phone')
    # ### end Alembic commands ###
