"""rename tables bills

Revision ID: 11bacacc20e0
Revises: 7a329620efff
Create Date: 2025-02-17 05:00:01.132410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11bacacc20e0'
down_revision = '7a329620efff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bot_bills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('plain_text', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('tochka_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('counterparty_account_number', sa.String(), nullable=True),
    sa.Column('payment_purpose', sa.String(), nullable=True),
    sa.Column('counterparty_bank_bic', sa.String(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.Column('corr_account', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'WAITING_FOR_APPROVAL', 'APPROVED', 'CANCELED', 'REJECTED', 'REQUESTED', 'PAID', 'ERROR', name='tgbillstatus'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tg_accounts.id'], ),
    sa.ForeignKeyConstraint(['tochka_bank_account_id'], ['tochka_bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_bills_id'), 'tg_bot_bills', ['id'], unique=False)
    op.create_table('tg_bot_bill_approvers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'APPROVED', 'CANCELED', name='tgbillapprovestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['tg_accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['tg_bot_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_bill_approvers_id'), 'tg_bot_bill_approvers', ['id'], unique=False)
    op.drop_index('ix_bill_approvers_id', table_name='bill_approvers')
    op.drop_table('bill_approvers')
    op.drop_index('ix_bills_id', table_name='bills')
    op.drop_table('bills')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_approvers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'approved', 'canceled', name='billapprovestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['tg_accounts.id'], name='bill_approvers_approver_id_fkey'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='bill_approvers_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bill_approvers_pkey')
    )
    op.create_index('ix_bill_approvers_id', 'bill_approvers', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plain_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tochka_bank_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('counterparty_account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('counterparty_bank_bic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('counterparty_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('corr_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'waiting_for_approval', 'approved', 'canceled', 'rejected', 'requested', 'paid', 'error', name='billstatus'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tg_accounts.id'], name='bills_created_by_fkey'),
    sa.ForeignKeyConstraint(['tochka_bank_account_id'], ['tochka_bank_accounts.id'], name='bills_tochka_bank_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bills_pkey')
    )
    op.create_index('ix_bills_id', 'bills', ['id'], unique=False)
    op.drop_index(op.f('ix_tg_bot_bill_approvers_id'), table_name='tg_bot_bill_approvers')
    op.drop_table('tg_bot_bill_approvers')
    op.drop_index(op.f('ix_tg_bot_bills_id'), table_name='tg_bot_bills')
    op.drop_table('tg_bot_bills')
    # ### end Alembic commands ###
