"""fix merge issues

Revision ID: 19a1d500a322
Revises: a37e79d73b65
Create Date: 2025-11-09 20:22:55.965692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a1d500a322'
down_revision = 'a37e79d73b65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs_sales_delivery_info', sa.Column('delivery_price', sa.Float(), nullable=True))
    op.add_column('nomenclature', sa.Column('chatting_percent', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('docs_purchases_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'docs_purchases', ['docs_purchases_id'], ['id'])
    op.add_column('price_types', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.add_column('relation_tg_cashboxes', sa.Column('shift_work_enabled', sa.Boolean(), nullable=True))
    op.add_column('warehouses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('warehouses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'longitude')
    op.drop_column('warehouses', 'latitude')
    op.drop_column('relation_tg_cashboxes', 'shift_work_enabled')
    op.drop_column('price_types', 'is_system')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'docs_purchases_id')
    op.drop_column('nomenclature', 'chatting_percent')
    op.drop_column('docs_sales_delivery_info', 'delivery_price')
    # ### end Alembic commands ###
