"""add utm

Revision ID: 1ba733de6ea7
Revises: 19a1d500a322
Create Date: 2025-11-10 07:42:42.073613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba733de6ea7'
down_revision = '19a1d500a322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_utm_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_term', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_name', sa.String(), nullable=True),
    sa.Column('utm_phone', sa.String(), nullable=True),
    sa.Column('utm_email', sa.String(), nullable=True),
    sa.Column('utm_leadid', sa.String(), nullable=True),
    sa.Column('utm_yclientid', sa.String(), nullable=True),
    sa.Column('utm_gaclientid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_utm_tags_id'), 'marketplace_utm_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_utm_tags_id'), table_name='marketplace_utm_tags')
    op.drop_table('marketplace_utm_tags')
    # ### end Alembic commands ###
