"""update view_events

Revision ID: 29b90590f950
Revises: 0562eb22c3eb
Create Date: 2025-11-08 07:51:43.728807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b90590f950'
down_revision = '0562eb22c3eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_view_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('listing_pos', sa.Integer(), nullable=True),
    sa.Column('listing_page', sa.Integer(), nullable=True),
    sa.Column('contragent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_view_events_id'), 'marketplace_view_events', ['id'], unique=False)
    op.drop_index('ix_view_events_id', table_name='view_events')
    op.drop_table('view_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing_pos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utm', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='view_events_pkey')
    )
    op.create_index('ix_view_events_id', 'view_events', ['id'], unique=False)
    op.drop_index(op.f('ix_marketplace_view_events_id'), table_name='marketplace_view_events')
    op.drop_table('marketplace_view_events')
    # ### end Alembic commands ###
