"""Nomenclature attributes and groups

Revision ID: 29ffbd0752b3
Revises: 7f4466d297af
Create Date: 2024-12-19 18:03:58.897009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ffbd0752b3'
down_revision = '7f4466d297af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomenclature_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_attribute_name')
    )
    op.create_index(op.f('ix_nomenclature_attributes_id'), 'nomenclature_attributes', ['id'], unique=False)
    op.create_table('nomenclature_attributes_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['nomenclature_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomenclature_attributes_value_id'), 'nomenclature_attributes_value', ['id'], unique=False)
    op.create_table('nomenclature_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenclature_id', name='uq_variant_per_nomenclature')
    )
    op.create_index(op.f('ix_nomenclature_groups_id'), 'nomenclature_groups', ['id'], unique=False)
    op.create_unique_constraint(None, 'amo_contacts', ['amo_install_group_id', 'ext_id'])
    op.create_unique_constraint(None, 'amo_lead_pipelines', ['amo_install_group_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_lead_statuses', ['pipeline_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_leads', ['amo_install_group_id', 'amo_id'])
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'amo_leads', type_='unique')
    op.drop_constraint(None, 'amo_lead_statuses', type_='unique')
    op.drop_constraint(None, 'amo_lead_pipelines', type_='unique')
    op.drop_constraint(None, 'amo_contacts', type_='unique')
    op.drop_index(op.f('ix_nomenclature_groups_id'), table_name='nomenclature_groups')
    op.drop_table('nomenclature_groups')
    op.drop_index(op.f('ix_nomenclature_attributes_value_id'), table_name='nomenclature_attributes_value')
    op.drop_table('nomenclature_attributes_value')
    op.drop_index(op.f('ix_nomenclature_attributes_id'), table_name='nomenclature_attributes')
    op.drop_table('nomenclature_attributes')
    # ### end Alembic commands ###
