"""add_entity_hash_table

Revision ID: 3a00d7970a8c
Revises: e47810d2387e
Create Date: 2025-08-11 23:00:09.918215

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '3a00d7970a8c'
down_revision = '1853c50d00b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('nomenclature', 'warehouses', name='hashableobject'), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hash')
    # ### end Alembic commands ###