"""new rows in warehouse: schedule

Revision ID: 3a1e219d4e80
Revises: 48b9f366baa8
Create Date: 2025-12-24 13:19:42.459012

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3a1e219d4e80"
down_revision = "48b9f366baa8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "warehouses",
        sa.Column(
            "shop_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "warehouses",
        sa.Column(
            "delivery_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warehouses", "delivery_schedule")
    op.drop_column("warehouses", "shop_schedule")
    # ### end Alembic commands ###
