"""check for shedule

Revision ID: 48b9f366baa8
Revises: aff18edcc3dd
Create Date: 2025-12-24 11:55:17.410519

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48b9f366baa8"
down_revision = "aff18edcc3dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cashbox_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cashbox_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("time_from", sa.Time(), nullable=True),
        sa.Column("time_to", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "day_of_week >= 0 AND day_of_week <= 6", name="ck_cashbox_schedule_day"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cashbox_id", "type", "day_of_week", name="uq_cashbox_schedule_day"
        ),
    )
    op.create_index(
        op.f("ix_cashbox_schedule_cashbox_id"),
        "cashbox_schedule",
        ["cashbox_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cashbox_schedule_cashbox_id"), table_name="cashbox_schedule")
    op.drop_table("cashbox_schedule")
    # ### end Alembic commands ###
