"""add tech cards

Revision ID: 4e29c4778eae
Revises: dfa79fb8b227
Create Date: 2025-07-07 22:16:03.382096

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4e29c4778eae"
down_revision = "dfa79fb8b227"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tech_cards",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "card_type",
            sa.Enum("reference", "automatic", name="card_type"),
            nullable=False,
        ),
        sa.Column("auto_produce", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "canceled", "deleted", name="status"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["relation_tg_cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tech_card_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tech_card_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nomenclature_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("gross_weight", sa.Float(), nullable=True),
        sa.Column("net_weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["nomenclature_id"],
            ["nomenclature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tech_card_id"],
            ["tech_cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tech_operations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tech_card_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("output_quantity", sa.Float(), nullable=False),
        sa.Column("from_warehouse_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("to_warehouse_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nomenclature_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "canceled", "deleted", name="status"),
            nullable=True,
        ),
        sa.Column("production_order_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("consumption_order_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["nomenclature_id"],
            ["nomenclature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tech_card_id"],
            ["tech_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["relation_tg_cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tech_operation_components",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("operation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("gross_weight", sa.Float(), nullable=True),
        sa.Column("net_weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["tech_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tech_operation_payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("operation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["tech_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tech_operation_payments")
    op.drop_table("tech_operation_components")
    op.drop_table("tech_operations")
    op.drop_table("tech_card_items")
    op.drop_table("tech_cards")
    # ### end Alembic commands ###
