"""warehouses coordinates + deprecated location table

Revision ID: 5d9b4fbae033
Revises: dbdfe6ebbe14
Create Date: 2025-08-24 16:12:25.683014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9b4fbae033'
down_revision = 'dbdfe6ebbe14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nomenclature_location_fkey', 'nomenclature', type_='foreignkey')
    op.drop_column('nomenclature', 'location')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_table('locations')
    op.add_column('warehouses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('warehouses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'longitude')
    op.drop_column('warehouses', 'latitude')
    op.add_column('nomenclature', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('nomenclature_location_fkey', 'nomenclature', 'locations', ['location'], ['id'])
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('house', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apartment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locations_pkey')
    )
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    # ### end Alembic commands ###
