"""entity-hash-table-partitioning

Revision ID: 61daf2cd92aa
Revises: 170143dc7ab4
Create Date: 2025-08-20 19:08:31.216599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61daf2cd92aa'
down_revision = '170143dc7ab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_hash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('warehouses_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouses_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclature_hash',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hash')
    op.add_column('nomenclature', sa.Column('chatting_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'chatting_percent')
    op.create_table('hash',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('nomenclature', 'warehouses', name='hashableobject'), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hash_pkey')
    )
    op.drop_table('nomenclature_hash')
    op.drop_table('warehouse_hash')
    # ### end Alembic commands ###
