"""add payment_past_edit_days

Revision ID: 6783addfadde
Revises: 7f34773f5e73
Create Date: 2025-08-06 09:53:33.464567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6783addfadde'
down_revision = '7f34773f5e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diadok_install_id', table_name='diadok_install')
    op.drop_table('diadok_install')
    op.create_unique_constraint(None, 'amo_contacts', ['amo_install_group_id', 'ext_id'])
    op.create_unique_constraint(None, 'amo_lead_pipelines', ['amo_install_group_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_lead_statuses', ['pipeline_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_leads', ['amo_install_group_id', 'amo_id'])
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    op.create_foreign_key(None, 'categories', 'pictures', ['photo_id'], ['id'])
    op.add_column('tg_accounts', sa.Column('payment_past_edit_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tg_bot_bill_approvers_id'), 'tg_bot_bill_approvers', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bot_bills_id'), 'tg_bot_bills', ['id'], unique=False)
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yookassa_payments', 'payment_capture',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tg_bot_bills_id'), table_name='tg_bot_bills')
    op.drop_index(op.f('ix_tg_bot_bill_approvers_id'), table_name='tg_bot_bill_approvers')
    op.drop_column('tg_accounts', 'payment_past_edit_days')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'amo_leads', type_='unique')
    op.drop_constraint(None, 'amo_lead_statuses', type_='unique')
    op.drop_constraint(None, 'amo_lead_pipelines', type_='unique')
    op.drop_constraint(None, 'amo_contacts', type_='unique')
    op.create_table('diadok_install',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name='diadok_install_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='diadok_install_pkey')
    )
    op.create_index('ix_diadok_install_id', 'diadok_install', ['id'], unique=False)
    # ### end Alembic commands ###
