"""marketplace

Revision ID: 733d7fbf311e
Revises: 0917e7569759
Create Date: 2025-11-04 17:14:33.332777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '733d7fbf311e'
down_revision = '0917e7569759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('contagent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_reviews_id'), 'warehouse_reviews', ['id'], unique=False)
    op.create_table('warehouses_rating_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_rating_aggregates_id'), 'warehouses_rating_aggregates', ['id'], unique=False)
    op.create_table('favorites_nomenclatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('contagent_id', sa.Integer(), nullable=False),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_nomenclatures_id'), 'favorites_nomenclatures', ['id'], unique=False)
    op.drop_index('ix_mp_orders_customer_order_id', table_name='mp_orders')
    op.drop_index('ix_mp_orders_customer_order_item_id', table_name='mp_orders')
    op.drop_index('ix_mp_orders_id', table_name='mp_orders')
    op.drop_index('ix_mp_orders_seller_cashbox_id', table_name='mp_orders')
    op.drop_index('ix_mp_orders_seller_order_id', table_name='mp_orders')
    op.drop_table('mp_orders')
    op.drop_index('ix_favorites_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_customer_order_items_customer_order_id', table_name='customer_order_items')
    op.drop_index('ix_customer_order_items_id', table_name='customer_order_items')
    op.drop_index('ix_customer_order_items_product_id', table_name='customer_order_items')
    op.drop_index('ix_customer_order_items_seller_cashbox_id', table_name='customer_order_items')
    op.drop_table('customer_order_items')
    op.drop_table('location_rating_aggregates')
    op.drop_index('ix_customer_orders_customer_phone', table_name='customer_orders')
    op.drop_index('ix_customer_orders_id', table_name='customer_orders')
    op.drop_index('ix_customer_orders_order_id', table_name='customer_orders')
    op.drop_table('customer_orders')
    op.drop_index('ix_reviews_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_column('cashboxes', 'city')
    op.drop_column('cashboxes', 'geo_point')
    op.drop_column('cashboxes', 'public')
    op.add_column('docs_sales', sa.Column('is_marketplace_order', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('nomenclature', 'city')
    op.drop_column('nomenclature', 'geo_point')
    op.drop_column('nomenclature', 'public')
    op.add_column('warehouses', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'is_public')
    op.add_column('nomenclature', sa.Column('public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('nomenclature', sa.Column('geo_point', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nomenclature', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('docs_sales', 'is_marketplace_order')
    op.add_column('cashboxes', sa.Column('public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('cashboxes', sa.Column('geo_point', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cashboxes', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('utm', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    op.create_index('ix_reviews_id', 'reviews', ['id'], unique=False)
    op.create_table('customer_orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customer_orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customer_lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivery_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('utm_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utm_medium', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utm_campaign', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_customer_orders_order_id', 'customer_orders', ['order_id'], unique=False)
    op.create_index('ix_customer_orders_id', 'customer_orders', ['id'], unique=False)
    op.create_index('ix_customer_orders_customer_phone', 'customer_orders', ['customer_phone'], unique=False)
    op.create_table('location_rating_aggregates',
    sa.Column('location_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('avg_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('location_id', name='location_rating_aggregates_pkey')
    )
    op.create_table('customer_order_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customer_order_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('listing_pos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seller_cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_picker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_courier_id'], ['relation_tg_cashboxes.id'], name='customer_order_items_assigned_courier_id_fkey'),
    sa.ForeignKeyConstraint(['assigned_picker_id'], ['relation_tg_cashboxes.id'], name='customer_order_items_assigned_picker_id_fkey'),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_orders.id'], name='customer_order_items_customer_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['nomenclature.id'], name='customer_order_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['seller_cashbox_id'], ['cashboxes.id'], name='customer_order_items_seller_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_order_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_customer_order_items_seller_cashbox_id', 'customer_order_items', ['seller_cashbox_id'], unique=False)
    op.create_index('ix_customer_order_items_product_id', 'customer_order_items', ['product_id'], unique=False)
    op.create_index('ix_customer_order_items_id', 'customer_order_items', ['id'], unique=False)
    op.create_index('ix_customer_order_items_customer_order_id', 'customer_order_items', ['customer_order_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('utm', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_index('ix_favorites_id', 'favorites', ['id'], unique=False)
    op.create_table('mp_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_order_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seller_cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('delivery_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customer_lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_picker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('routing_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recipient_lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(), server_default=sa.text("'self'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_courier_id'], ['relation_tg_cashboxes.id'], name='mp_orders_assigned_courier_id_fkey'),
    sa.ForeignKeyConstraint(['assigned_picker_id'], ['relation_tg_cashboxes.id'], name='mp_orders_assigned_picker_id_fkey'),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_orders.id'], name='mp_orders_customer_order_id_fkey'),
    sa.ForeignKeyConstraint(['customer_order_item_id'], ['customer_order_items.id'], name='mp_orders_customer_order_item_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['nomenclature.id'], name='mp_orders_product_id_fkey'),
    sa.ForeignKeyConstraint(['seller_cashbox_id'], ['cashboxes.id'], name='mp_orders_seller_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mp_orders_pkey')
    )
    op.create_index('ix_mp_orders_seller_order_id', 'mp_orders', ['seller_order_id'], unique=False)
    op.create_index('ix_mp_orders_seller_cashbox_id', 'mp_orders', ['seller_cashbox_id'], unique=False)
    op.create_index('ix_mp_orders_id', 'mp_orders', ['id'], unique=False)
    op.create_index('ix_mp_orders_customer_order_item_id', 'mp_orders', ['customer_order_item_id'], unique=False)
    op.create_index('ix_mp_orders_customer_order_id', 'mp_orders', ['customer_order_id'], unique=False)
    op.drop_index(op.f('ix_favorites_nomenclatures_id'), table_name='favorites_nomenclatures')
    op.drop_table('favorites_nomenclatures')
    op.drop_index(op.f('ix_warehouses_rating_aggregates_id'), table_name='warehouses_rating_aggregates')
    op.drop_table('warehouses_rating_aggregates')
    op.drop_index(op.f('ix_warehouse_reviews_id'), table_name='warehouse_reviews')
    op.drop_table('warehouse_reviews')
    # ### end Alembic commands ###
