"""bills

Revision ID: 7a329620efff
Revises: a2eed5d94a9e
Create Date: 2025-02-13 18:00:49.271511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a329620efff'
down_revision = 'a2eed5d94a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('plain_text', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('tochka_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('counterparty_account_number', sa.String(), nullable=True),
    sa.Column('payment_purpose', sa.String(), nullable=True),
    sa.Column('counterparty_bank_bic', sa.String(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.Column('corr_account', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'waiting_for_approval', 'approved', 'canceled', 'rejected', 'requested', 'paid', 'error', name='billstatus'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tg_accounts.id'], ),
    sa.ForeignKeyConstraint(['tochka_bank_account_id'], ['tochka_bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_table('bill_approvers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'approved', 'canceled', name='billapprovestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['tg_accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_approvers_id'), 'bill_approvers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_approvers_id'), table_name='bill_approvers')
    op.drop_table('bill_approvers')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    op.execute("DROP TYPE billstatus")
    op.execute("DROP TYPE billapprovestatus")
    # ### end Alembic commands ###
