"""add fields to contr

Revision ID: 7ae789d0afe8
Revises: fab805a9d974
Create Date: 2024-11-09 23:23:29.060643

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ae789d0afe8'
down_revision = 'dbbe06a4083d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_events_photo', 'id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    op.add_column('contragents', sa.Column('additional_phones', sa.String(), nullable=True))
    op.add_column('contragents', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contragents', 'gender')
    op.drop_column('contragents', 'additional_phones')
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    autoincrement=True)
    # ### end Alembic commands ###
