"""add timezone

Revision ID: 86df9041b650
Revises: 03c97d9e42f7
Create Date: 2025-08-07 12:47:04.535067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86df9041b650'
down_revision = '03c97d9e42f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_tg_cashboxes', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_tg_cashboxes', 'timezone')
    # ### end Alembic commands ###
