"""bills data

Revision ID: 98f082dd3052
Revises: fd38c4a3442f
Create Date: 2025-02-10 21:47:44.601898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f082dd3052'
down_revision = 'fd38c4a3442f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('tochka_bank_account_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('bills', sa.Column('pc', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('reason', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('bic', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('seller', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('inn_seller', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('inn_buyer', sa.String(), nullable=False))
    op.add_column('bills', sa.Column('corr_account', sa.String(), nullable=False))
    op.alter_column('bills', 'plain_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'bills', 'tochka_bank_accounts', ['tochka_bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.alter_column('bills', 'plain_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('bills', 'corr_account')
    op.drop_column('bills', 'inn_buyer')
    op.drop_column('bills', 'inn_seller')
    op.drop_column('bills', 'seller')
    op.drop_column('bills', 'bic')
    op.drop_column('bills', 'reason')
    op.drop_column('bills', 'pc')
    op.drop_column('bills', 'amount')
    op.drop_column('bills', 'tochka_bank_account_id')
    # ### end Alembic commands ###
