"""add_entity_id_in_hash

Revision ID: 9c121f40e783
Revises: 3a00d7970a8c
Create Date: 2025-08-12 01:57:23.166556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c121f40e783'
down_revision = '3a00d7970a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hash', sa.Column('entity_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hash', 'entity_id')
    # ### end Alembic commands ###
