"""add files table

Revision ID: 9d798342e39e
Revises: 8a35bb3f1dc4
Create Date: 2025-12-12 19:39:37.326473

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d798342e39e"
down_revision = "8a35bb3f1dc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("extension", sa.String(length=10), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.Column("cashbox", sa.Integer(), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["cashbox"],
            ["cashboxes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["relation_tg_cashboxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.drop_index("ix_diadok_install_id", table_name="diadok_install")
    op.drop_table("diadok_install")
    op.create_unique_constraint(
        None, "amo_contacts", ["amo_install_group_id", "ext_id"]
    )
    op.drop_constraint(
        "amo_contacts_double_orig_id_fkey", "amo_contacts_double", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "amo_contacts_double", "amo_contacts", ["orig_id"], ["id"]
    )
    op.drop_constraint(
        "amo_entity_custom_fields_contact_id_fkey",
        "amo_entity_custom_fields",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "amo_entity_custom_fields", "amo_contacts", ["contact_id"], ["id"]
    )
    op.create_unique_constraint(
        None, "amo_lead_pipelines", ["amo_install_group_id", "amo_id"]
    )
    op.create_unique_constraint(None, "amo_lead_statuses", ["pipeline_id", "amo_id"])
    op.create_unique_constraint(None, "amo_leads", ["amo_install_group_id", "amo_id"])
    op.alter_column(
        "booking_events_photo",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f("ix_segments_tags_id"), "segments_tags", ["id"], unique=False)
    op.create_foreign_key(
        None, "tech_operation_components", "nomenclature", ["nomeclature_id"], ["id"]
    )
    op.create_index(
        op.f("ix_tg_bot_bill_approvers_id"),
        "tg_bot_bill_approvers",
        ["id"],
        unique=False,
    )
    op.create_index(op.f("ix_tg_bot_bills_id"), "tg_bot_bills", ["id"], unique=False)
    op.alter_column(
        "yookassa_payments",
        "payment_capture",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "yookassa_payments",
        "payment_capture",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_tg_bot_bills_id"), table_name="tg_bot_bills")
    op.drop_index(
        op.f("ix_tg_bot_bill_approvers_id"), table_name="tg_bot_bill_approvers"
    )
    op.drop_constraint(None, "tech_operation_components", type_="foreignkey")
    op.drop_index(op.f("ix_segments_tags_id"), table_name="segments_tags")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.alter_column(
        "booking_events_photo",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_constraint(None, "amo_leads", type_="unique")
    op.drop_constraint(None, "amo_lead_statuses", type_="unique")
    op.drop_constraint(None, "amo_lead_pipelines", type_="unique")
    op.drop_constraint(None, "amo_entity_custom_fields", type_="foreignkey")
    op.create_foreign_key(
        "amo_entity_custom_fields_contact_id_fkey",
        "amo_entity_custom_fields",
        "amo_contacts",
        ["contact_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "amo_contacts_double", type_="foreignkey")
    op.create_foreign_key(
        "amo_contacts_double_orig_id_fkey",
        "amo_contacts_double",
        "amo_contacts",
        ["orig_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "amo_contacts", type_="unique")
    op.create_table(
        "diadok_install",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("cashbox_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["cashbox_id"], ["cashboxes.id"], name="diadok_install_cashbox_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="diadok_install_pkey"),
    )
    op.create_index("ix_diadok_install_id", "diadok_install", ["id"], unique=False)
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
