"""add_lead_contacts

Revision ID: 9fc329b56861
Revises: f82fc5198d96
Create Date: 2025-06-25 20:52:36.161795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc329b56861'
down_revision = 'f82fc5198d96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_lead_contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amo_install_group_id', sa.Integer(), nullable=True),
        sa.Column('lead_id', sa.BigInteger(), nullable=True),
        sa.Column('contact_id', sa.BigInteger(), nullable=True),
        sa.Column('is_main', sa.Boolean(), server_default='true', nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['amo_install_group_id'], ['amo_install_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_lead_contacts_id'), 'amo_lead_contacts', ['id'], unique=False)
    op.create_index('uq_amo_lead_contacts_group_lead_contact', 'amo_lead_contacts', ['amo_install_group_id', 'lead_id', 'contact_id'], unique=True, postgresql_where=sa.text('amo_install_group_id IS NOT NULL AND lead_id IS NOT NULL AND contact_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_amo_lead_contacts_group_lead_contact', table_name='amo_lead_contacts', postgresql_where=sa.text('amo_install_group_id IS NOT NULL AND lead_id IS NOT NULL AND contact_id IS NOT NULL'))
    op.drop_index(op.f('ix_amo_lead_contacts_id'), table_name='amo_lead_contacts')
    op.drop_table('amo_lead_contacts')
    # ### end Alembic commands ###
