"""update marketplace_rating_aggregates

Revision ID: a37e79d73b65
Revises: ae6d5f57cb4a
Create Date: 2025-11-09 19:37:34.418796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a37e79d73b65'
down_revision = 'ae6d5f57cb4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_rating_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_rating_aggregates_id'), 'marketplace_rating_aggregates', ['id'], unique=False)
    op.drop_index('ix_warehouses_rating_aggregates_id', table_name='warehouses_rating_aggregates')
    op.drop_table('warehouses_rating_aggregates')
    op.drop_index('ix_qr_codes_id', table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qr_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='qr_codes_pkey'),
    sa.UniqueConstraint('qr_hash', name='qr_codes_qr_hash_key')
    )
    op.create_index('ix_qr_codes_id', 'qr_codes', ['id'], unique=False)
    op.create_table('warehouses_rating_aggregates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='warehouses_rating_aggregates_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='warehouses_rating_aggregates_pkey')
    )
    op.create_index('ix_warehouses_rating_aggregates_id', 'warehouses_rating_aggregates', ['id'], unique=False)
    op.drop_index(op.f('ix_marketplace_rating_aggregates_id'), table_name='marketplace_rating_aggregates')
    op.drop_table('marketplace_rating_aggregates')
    # ### end Alembic commands ###
