"""fix_hashable_object_type

Revision ID: ac56989e137f
Revises: 9c121f40e783
Create Date: 2025-08-12 02:14:18.277292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac56989e137f'
down_revision = '9c121f40e783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
