"""update marketplace_reviews

Revision ID: ae6d5f57cb4a
Revises: c38d656839b4
Create Date: 2025-11-09 10:50:17.554964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae6d5f57cb4a'
down_revision = 'c38d656839b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('contagent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='visible', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_reviews_id'), 'marketplace_reviews', ['id'], unique=False)
    op.drop_index('ix_warehouse_reviews_id', table_name='warehouse_reviews')
    op.drop_table('warehouse_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contagent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('utm', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contagent_id'], ['contragents.id'], name='warehouse_reviews_contagent_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='warehouse_reviews_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='warehouse_reviews_pkey')
    )
    op.create_index('ix_warehouse_reviews_id', 'warehouse_reviews', ['id'], unique=False)
    op.drop_index(op.f('ix_marketplace_reviews_id'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')
    # ### end Alembic commands ###
