"""marketplace

Revision ID: b89cc2159913
Revises: 0053a68ec9ec
Create Date: 2025-11-02 21:55:35.989421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b89cc2159913'
down_revision = '0053a68ec9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_lat', sa.Float(), nullable=True),
    sa.Column('customer_lon', sa.Float(), nullable=True),
    sa.Column('delivery_type', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('delivery_comment', sa.String(), nullable=True),
    sa.Column('delivery_preferred_time', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_orders_customer_phone'), 'customer_orders', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_customer_orders_id'), 'customer_orders', ['id'], unique=False)
    op.create_index(op.f('ix_customer_orders_order_id'), 'customer_orders', ['order_id'], unique=True)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=False),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('global_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['global_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_categories_id'), 'global_categories', ['id'], unique=False)
    op.create_table('location_rating_aggregates',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_hash', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_hash')
    )
    op.create_index(op.f('ix_qr_codes_id'), 'qr_codes', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('view_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('listing_pos', sa.Integer(), nullable=True),
    sa.Column('listing_page', sa.Integer(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_events_id'), 'view_events', ['id'], unique=False)
    op.create_table('customer_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('listing_pos', sa.Integer(), nullable=True),
    sa.Column('listing_page', sa.Integer(), nullable=True),
    sa.Column('seller_cashbox_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('assigned_picker_id', sa.Integer(), nullable=True),
    sa.Column('assigned_courier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_courier_id'], ['relation_tg_cashboxes.id'], ),
    sa.ForeignKeyConstraint(['assigned_picker_id'], ['relation_tg_cashboxes.id'], ),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['nomenclature.id'], ),
    sa.ForeignKeyConstraint(['seller_cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_items_customer_order_id'), 'customer_order_items', ['customer_order_id'], unique=False)
    op.create_index(op.f('ix_customer_order_items_id'), 'customer_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_customer_order_items_product_id'), 'customer_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_order_items_seller_cashbox_id'), 'customer_order_items', ['seller_cashbox_id'], unique=False)
    op.create_table('mp_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_order_item_id', sa.Integer(), nullable=False),
    sa.Column('seller_order_id', sa.String(), nullable=False),
    sa.Column('seller_cashbox_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('delivery_type', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('delivery_comment', sa.String(), nullable=True),
    sa.Column('delivery_preferred_time', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_lat', sa.Float(), nullable=True),
    sa.Column('customer_lon', sa.Float(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('assigned_picker_id', sa.Integer(), nullable=True),
    sa.Column('assigned_courier_id', sa.Integer(), nullable=True),
    sa.Column('routing_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_courier_id'], ['relation_tg_cashboxes.id'], ),
    sa.ForeignKeyConstraint(['assigned_picker_id'], ['relation_tg_cashboxes.id'], ),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_orders.id'], ),
    sa.ForeignKeyConstraint(['customer_order_item_id'], ['customer_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['nomenclature.id'], ),
    sa.ForeignKeyConstraint(['seller_cashbox_id'], ['cashboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_orders_customer_order_id'), 'mp_orders', ['customer_order_id'], unique=False)
    op.create_index(op.f('ix_mp_orders_customer_order_item_id'), 'mp_orders', ['customer_order_item_id'], unique=False)
    op.create_index(op.f('ix_mp_orders_id'), 'mp_orders', ['id'], unique=False)
    op.create_index(op.f('ix_mp_orders_seller_cashbox_id'), 'mp_orders', ['seller_cashbox_id'], unique=False)
    op.create_index(op.f('ix_mp_orders_seller_order_id'), 'mp_orders', ['seller_order_id'], unique=True)
    op.add_column('cashboxes', sa.Column('public', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('cashboxes', sa.Column('geo_point', sa.String(), nullable=True))
    op.add_column('cashboxes', sa.Column('city', sa.String(length=100), nullable=True))
    op.drop_column('docs_sales_delivery_info', 'delivery_price')
    op.add_column('nomenclature', sa.Column('public', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('nomenclature', sa.Column('geo_point', sa.String(), nullable=True))
    op.add_column('nomenclature', sa.Column('city', sa.String(length=100), nullable=True))
    op.drop_column('nomenclature', 'chatting_percent')
    op.drop_column('price_types', 'is_system')
    op.drop_column('relation_tg_cashboxes', 'shift_work_enabled')
    op.drop_column('warehouses', 'latitude')
    op.drop_column('warehouses', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('relation_tg_cashboxes', sa.Column('shift_work_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('price_types', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('nomenclature', sa.Column('chatting_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('nomenclature', 'city')
    op.drop_column('nomenclature', 'geo_point')
    op.drop_column('nomenclature', 'public')
    op.add_column('docs_sales_delivery_info', sa.Column('delivery_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('cashboxes', 'city')
    op.drop_column('cashboxes', 'geo_point')
    op.drop_column('cashboxes', 'public')
    op.drop_index(op.f('ix_mp_orders_seller_order_id'), table_name='mp_orders')
    op.drop_index(op.f('ix_mp_orders_seller_cashbox_id'), table_name='mp_orders')
    op.drop_index(op.f('ix_mp_orders_id'), table_name='mp_orders')
    op.drop_index(op.f('ix_mp_orders_customer_order_item_id'), table_name='mp_orders')
    op.drop_index(op.f('ix_mp_orders_customer_order_id'), table_name='mp_orders')
    op.drop_table('mp_orders')
    op.drop_index(op.f('ix_customer_order_items_seller_cashbox_id'), table_name='customer_order_items')
    op.drop_index(op.f('ix_customer_order_items_product_id'), table_name='customer_order_items')
    op.drop_index(op.f('ix_customer_order_items_id'), table_name='customer_order_items')
    op.drop_index(op.f('ix_customer_order_items_customer_order_id'), table_name='customer_order_items')
    op.drop_table('customer_order_items')
    op.drop_index(op.f('ix_view_events_id'), table_name='view_events')
    op.drop_table('view_events')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_qr_codes_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_table('location_rating_aggregates')
    op.drop_index(op.f('ix_global_categories_id'), table_name='global_categories')
    op.drop_table('global_categories')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_customer_orders_order_id'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_id'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_customer_phone'), table_name='customer_orders')
    op.drop_table('customer_orders')
    # ### end Alembic commands ###
