"""update view_events

Revision ID: c38d656839b4
Revises: 29b90590f950
Create Date: 2025-11-08 08:24:10.396543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38d656839b4'
down_revision = '29b90590f950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_view_events', sa.Column('cashbox_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marketplace_view_events', 'cashboxes', ['cashbox_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplace_view_events', type_='foreignkey')
    op.drop_column('marketplace_view_events', 'cashbox_id')
    # ### end Alembic commands ###
