"""update_hash_table

Revision ID: cd96cbf9e304
Revises: 3a00d7970a8c
Create Date: 2025-08-12 00:21:04.969635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd96cbf9e304'
down_revision = '3a00d7970a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('hash', sa.Column('entity_id', sa.Integer(), nullable=False))
    # op.drop_constraint('nomenclature_hash_fkey', 'nomenclature', type_='foreignkey')
    # op.drop_column('nomenclature', 'hash')
    # op.drop_constraint('warehouses_hash_fkey', 'warehouses', type_='foreignkey')
    # op.drop_column('warehouses', 'hash')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('warehouses', sa.Column('hash', sa.BIGINT(), autoincrement=False, nullable=True))
    # op.create_foreign_key('warehouses_hash_fkey', 'warehouses', 'hash', ['hash'], ['id'])
    # op.add_column('nomenclature', sa.Column('hash', sa.BIGINT(), autoincrement=False, nullable=True))
    # op.create_foreign_key('nomenclature_hash_fkey', 'nomenclature', 'hash', ['hash'], ['id'])
    # op.drop_column('hash', 'entity_id')
    # ### end Alembic commands ###
    pass