"""add_chatting_percent_in_nomenclature

Revision ID: e47810d2387e
Revises: 1853c50d00b7
Create Date: 2025-08-11 20:11:27.206429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47810d2387e'
down_revision = '1853c50d00b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('chatting_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'chatting_percent')
    # ### end Alembic commands ###
