"""Docs_sales delivery address, Nomeclature minimum order, web_description, tags

Revision ID: f604396f056e
Revises: e3f6f0b1ee7a
Create Date: 2024-12-24 17:53:36.509351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f604396f056e'
down_revision = 'e3f6f0b1ee7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs_sales', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('nomenclature', sa.Column('web_description', sa.String(), nullable=True))
    op.add_column('nomenclature', sa.Column('minimum_order', sa.Integer(), nullable=True))
    op.add_column('nomenclature', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'tags')
    op.drop_column('nomenclature', 'minimum_order')
    op.drop_column('nomenclature', 'web_description')
    op.drop_column('docs_sales', 'delivery_address')
    # ### end Alembic commands ###
