"""bills

Revision ID: fd38c4a3442f
Revises: a2eed5d94a9e
Create Date: 2025-02-07 15:28:32.212405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd38c4a3442f'
down_revision = 'a2eed5d94a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('new', 'approved', 'canceled', 'paid', 'error', name='billstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tg_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_table('bill_approvers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('plain_text', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('new', 'approved', 'canceled', name='billapprovestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['tg_accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_approvers_id'), 'bill_approvers', ['id'], unique=False)
    op.drop_index('ix_diadok_install_id', table_name='diadok_install')
    op.drop_table('diadok_install')
    op.create_unique_constraint(None, 'amo_contacts', ['amo_install_group_id', 'ext_id'])
    op.create_unique_constraint(None, 'amo_lead_pipelines', ['amo_install_group_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_lead_statuses', ['pipeline_id', 'amo_id'])
    op.create_unique_constraint(None, 'amo_leads', ['amo_install_group_id', 'amo_id'])
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_booking_events_photo_id', table_name='booking_events_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_booking_events_photo_id', 'booking_events_photo', ['id'], unique=False)
    op.alter_column('booking_events_photo', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'amo_leads', type_='unique')
    op.drop_constraint(None, 'amo_lead_statuses', type_='unique')
    op.drop_constraint(None, 'amo_lead_pipelines', type_='unique')
    op.drop_constraint(None, 'amo_contacts', type_='unique')
    op.create_table('diadok_install',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cashbox_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name='diadok_install_cashbox_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='diadok_install_pkey')
    )
    op.create_index('ix_diadok_install_id', 'diadok_install', ['id'], unique=False)
    op.drop_index(op.f('ix_bill_approvers_id'), table_name='bill_approvers')
    op.drop_table('bill_approvers')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
